config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root to: "welcome#index"

  get "welcome/index"

  concern :imageable do
    resources :images
  end
  resources :images
  resources :users, concerns: :imageable
  resources :posts
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  has_many :imageations, dependent: :destroy

  has_one_attached :attachment, dependent: :destroy
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  include Behaveable::ResourceFinder
  include Behaveable::RouteExtractor

  before_action :set_image, only: %i[show edit update destroy]

  # GET /images or /images.json
  def index
    @images = imageable.all

    respond_to do |format|
      format.html { render :index, status: :ok, location: extract(behaveable: @behaveable) }
      format.json { render json: @images, status: :ok, location: extract(behaveable: @behaveable) }
    end
  end

  # GET /images/1 or /images/1.json
  def show
    respond_to do |format|
      format.html { render :show, status: :ok, location: polymorphic_url([@behaveable, @image]) }
      format.json { render json: @image, status: :ok, location: polymorphic_url([@behaveable, @image]) }
    end
  end

  # GET /images/new
  def new
    @image = imageable.new
    respond_to do |format|
      format.html { render :new, status: :ok, location: polymorphic_url([@behaveable, @image]) }
      format.json { render json: @image, status: :ok, location: polymorphic_url([@behaveable, @image]) }
    end
  end

  # GET /images/1/edit
  def edit
    respond_to do |format|
      format.html { render :edit, status: :ok, location: extract(behaveable: @behaveable, resource: @image) }
      format.json do
        render json: @image, status: :ok, location: extract(behaveable: @behaveable, resource: @image)
      end
    end
  end

  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength

  # POST /images or /images.json
  def create
    @image = imageable.new(image_params)

    respond_to do |format|
      @image.transaction do
        if @image.save
          imageable << @image if @behaveable

          @image.attachment.attach(params[:image][:attachment]) if params[:image][:attachment]
          @image.attachment.analyze if @image.attachment.attached?

          format.html do
            redirect_to polymorphic_url([@behaveable, @image]), notice: "Image was successfully created."
          end
          format.json do
            render json: @image, status: :created, location: polymorphic_url([@behaveable, @image])
          end
        else
          format.html do
            render :new, status: :unprocessable_entity, location: polymorphic_url([@behaveable, @image])
          end
          format.json do
            render json: @image.errors, status: :unprocessable_entity,
                   location: polymorphic_url([@behaveable, @image])
          end
        end
      end
    end
  end

  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Metrics/MethodLength

  # PATCH/PUT /images/1 or /images/1.json
  def update # rubocop:disable Metrics/MethodLength
    respond_to do |format|
      if @image.update(image_params)
        format.html do
          redirect_to polymorphic_url([@behaveable, @image]), notice: "Image was successfully updated."
        end
        format.json { render :edit, status: :ok, location: polymorphic_url([@behaveable, @image]) }
      else
        format.html do
          render :edit, status: :unprocessable_entity,
                        location: polymorphic_url([@behaveable, @image])
        end
        format.json do
          render json: @image.errors, status: :unprocessable_entity,
                 location: polymorphic_url([@behaveable, @image])
        end
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to extract(behaveable: @behaveable), notice: "Image was successfully destroyed." }
      format.json { head :no_content, location: extract(behaveable: @behaveable) }
    end
  end

  private

  # Get Image context object.
  #
  # ==== Returns
  # * <tt>ActiveRecord</tt> - Imageable's images or Image.
  def imageable
    @behaveable ||= behaveable
    @behaveable ? @behaveable.images : Image
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = imageable.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(
      :name,
      :attachment
    )
  end
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper
  class RouteHelperError < StandardError; end

  def nested_helper_url(resource_name:, action: nil, behaveable: nil, resource: nil)
    location_url = location_url(resource_name: resource_name, action: action, behaveable: behaveable,
                                resource: resource)
    return regular(location_url: location_url, resource: resource) unless behaveable

    nested(location_url: location_url, behaveable: behaveable, resource: resource)
  end

  private

  def regular(location_url:, resource: nil)
    return send(location_url) unless resource

    send(location_url, resource)
  end

  def nested(location_url:, behaveable:, resource: nil)
    return send(location_url, behaveable) unless resource

    # action = resource_persisted?(resource) ? :update : :create
    # send(location_url, behaveable, resource, action: action)
    send(location_url, behaveable, resource)
  end

  # rubocop:disable Metrics/CyclomaticComplexity
  # rubocop:disable Metrics/MethodLength

  def location_url(resource_name:, action: nil, behaveable: nil, resource: nil)
    inflected_name = resource_name_inflection(resource_name: resource_name, resource: resource)
    behaveable_name = behaveable_name_from(behaveable) # Always singular

    url = behaveable ? "#{behaveable_name}_#{inflected_name}_url" : "#{inflected_name}_url"

    case action&.to_sym
    when :edit
      raise RouteHelperError, "Edit Route Need a Resource" unless resource

      "edit_#{url}"
    when :new
      raise RouteHelperError, "New Route Need a Resource" unless resource
      raise RouteHelperError, "Persisted Resource For New Route" if resource_persisted?(resource)

      "new_#{url}"
    else
      url
    end
  end

  # rubocop:enable Metrics/CyclomaticComplexity
  # rubocop:enable Metrics/MethodLength

  def resource_name_inflection(resource_name:, resource:)
    inflection = resource ? "singular" : "plural"
    resource_name.send("#{inflection}ize")
  end

  def behaveable_name_from(behaveable)
    return unless behaveable

    behaveable.class.name.underscore
  end

  def resource_persisted?(resource)
    return resource.persisted? if resource.respond_to?(:persisted?)

    !resource.id.nil?
  end
end

app/views/images/_form.html.erb
<% method = image.persisted? ? :patch : :post %>
<%= form_with(scope: :image, url: polymorphic_url([@behaveable, image]), method: method, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.file_field :attachment, direct_upload: true %><br>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td>
          <% if image.attachment.attached? %>
            <%= image_tag url_for(image.attachment.variant(resize: "50x50").processed) %>
          <% else %>
            No Attachment
          <% end %>
        </td>
        <td><%= image.name %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>

<% if @image.attachment.attached? %>
  <% if @image.attachment.representable? %>
    <%= image_tag url_for(@image.attachment.representation(resize: "200x200").processed) %>
  <% else %>
    <%= image_tag url_for(@image.attachment), class: "variant-1" %>
  <% end %>
<% else %>
  No Attachment
<% end %>

<%= link_to 'Edit', nested_helper_url(resource_name: "images", action: :edit, behaveable: @behaveable, resource: @image) %> |
<%= link_to 'Back', nested_helper_url(resource_name: "images", behaveable: @behaveable) %>